version: '3'

volumes:
  django_static: {}
  postgres_dev_db: {}

services:
  web:
    restart: always
    image: labcodes/knowledge
    build:
      context: .
      dockerfile: ./conf/django/dev/Dockerfile
    links:
      - postgres
    volumes:
      - .:/app
      - django_static:/app/staticfiles
    env_file: .env
    ports:
      - 8080:8000
    depends_on:
      - postgres

  postgres:
    restart: always
    container_name: knowledge_db
    image: postgres:9.6.5
    volumes:
      - postgres_dev_db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5434:5432
