# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
