# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:40
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
