# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20170110_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created']},
        ),
    ]
